name: ie-bank-frontend
on:
  push:
    paths:
      - "**"
    branches:
      - "*"
  pull_request:
    branches:
      - main
    paths:
      - "**"
  workflow_dispatch:

env:
  FRONTEND_WEBAPP_DEV: apuliga-fe-dev
  FRONTEND_WEBAPP_UAT: apuliga-fe-uat

jobs:
  build-dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Debug - Print Variables (Dev)
        run: |
          echo "NODE_ENV: ${{ vars.NODE_ENV }}"
          echo "VUE_APP_ROOT_URL: ${{ vars.VUE_APP_ROOT_URL }}"
          echo "BASE_URL: ${{ vars.BASE_URL }}"
      - name: npm install, build, and test (Dev)
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          VUE_APP_ROOT_URL: ${{ vars.VUE_APP_ROOT_URL }}
          BASE_URL: ${{ vars.BASE_URL }}
        run: |
          npm ci
          npm run build -- --mode ${{ vars.NODE_ENV }}
      - name: Upload artifact for deployment job (Dev)
        uses: actions/upload-artifact@v4
        with:
          name: node-app-dev
          path: dist/

  build-uat:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Debug - Print Variables (UAT)
        run: |
          echo "NODE_ENV: ${{ vars.NODE_ENV }}"
          echo "VUE_APP_ROOT_URL: ${{ vars.VUE_APP_ROOT_URL }}"
          echo "BASE_URL: ${{ vars.BASE_URL }}"
      - name: npm install, build, and test (UAT)
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          VUE_APP_ROOT_URL: ${{ vars.VUE_APP_ROOT_URL }}
          BASE_URL: ${{ vars.BASE_URL }}
        run: |
          npm ci
          npm run build -- --mode ${{ vars.NODE_ENV }}
      - name: Upload artifact for deployment job (UAT)
        uses: actions/upload-artifact@v4
        with:
          name: node-app-uat
          path: dist/

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-dev
    environment:
      name: "Development"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_DEV }}
          package: .

  deploy-uat:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    needs: build-uat
    environment:
      name: "UAT"
      url: ${{ steps.deploy-to-webapp-uat.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Deploy to Azure Web App (UAT)"
        id: deploy-to-webapp-uat
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_UAT }}
          package: .
